attempting to add PEFT to tevatron
texttron/tevatron pull request #82
Opened 2023-04-11 20:22 UTC by MXueguang

2023-04-22 19:50 UTC, luyug requested changes

2023-04-22 19:50 UTC, luyug commented on src/tevatron/modeling/encoder.py
> +            peft_config = LoraConfig(task_type="Embedding", inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1)
do we want to make this configurable?

2023-04-22 19:50 UTC, luyug commented on src/tevatron/arguments.py
> +    peft: bool = field(default=False)
maybe lora as opposed to peft here (and also for the rest of the change

2024-05-19 17:18 UTC, MXueguang commented
this was done

2024-05-19 17:18 UTC, closed without merging